import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

print("==========================================================")
print("  GATP: PYTHON GEOSPATIAL VISUALIZER INITIALIZED")
print("==========================================================")

# 1. READ THE CSV FILES (Generated by your C++ engine)
try:
    print("[SYSTEM]: Loading geographic data from nodes.csv...")
    nodes_df = pd.read_csv('nodes.csv')
    
    print("[SYSTEM]: Loading transmission corridors from edges.csv...")
    edges_df = pd.read_csv('edges.csv')
except FileNotFoundError:
    print("[ERROR]: Could not find CSV files. Make sure they are in the same folder.")
    exit()

# 2. INITIALIZE THE NETWORK GRAPH
G = nx.Graph()
positions = {}
node_colors = []

# 3. PLOT THE CITIES (NODES)
for index, row in nodes_df.iterrows():
    node_id = row['NodeID']
    city_name = row['CityName']
    
    # Use real GPS coordinates for the map (X = Longitude, Y = Latitude)
    positions[node_id] = (row['Longitude'], row['Latitude'])
    G.add_node(node_id, label=city_name)
    
    # 🚨 DYNAMIC COLORING: If Protest Score is highly dangerous (> 0.5), color it RED
    if row['ProtestScore'] > 0.5:
        node_colors.append('#E74C3C') # Danger Red (Morbi)
    else:
        node_colors.append('#2ECC71') # Safe Green

# 4. PLOT THE POWER LINES (EDGES)
for index, row in edges_df.iterrows():
    G.add_edge(row['SourceID'], row['DestID'])

# 5. RENDER THE GRAPHICS
print("[SYSTEM]: Rendering Geospatial Map...")
plt.figure(figsize=(10, 8), facecolor='#F8F9F9')

# Draw the high-tension wires (Grey lines)
nx.draw_networkx_edges(G, positions, width=3, edge_color='#BDC3C7', alpha=0.8)

# Draw the infrastructure nodes (Colored dots)
nx.draw_networkx_nodes(G, positions, node_size=1200, node_color=node_colors, edgecolors='black', linewidths=1.5)

# Add the City Names
labels = nx.get_node_attributes(G, 'label')
nx.draw_networkx_labels(G, positions, labels, font_size=11, font_weight="bold", font_color='black')

# Add Titles and Legend
plt.title("GATP: Gujarat Transmission Infrastructure Map", fontsize=16, fontweight='bold', pad=20)
plt.figtext(0.5, 0.02, "Green = Standard Clearance  |  Red = Critical Sociological Friction (Farmer Protests)", ha="center", fontsize=12, bbox={"facecolor":"white", "alpha":0.8, "pad":5})

# Display the final UI
plt.axis("off") # Hide standard graph borders for a cleaner look
plt.tight_layout()
plt.show()